"""add feature tables

Revision ID: 83f355add86d
Revises: 
Create Date: 2026-03-08 12:20:29.817528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83f355add86d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matchup_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(length=10), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=True),
    sa.Column('opponent_team_id', sa.Integer(), nullable=False),
    sa.Column('matchup_games_played', sa.Integer(), nullable=True),
    sa.Column('has_matchup_history', sa.Boolean(), nullable=False),
    sa.Column('matchup_avg_points', sa.Float(), nullable=True),
    sa.Column('matchup_avg_rebounds', sa.Float(), nullable=True),
    sa.Column('matchup_avg_assists', sa.Float(), nullable=True),
    sa.Column('matchup_avg_fg_pct', sa.Float(), nullable=True),
    sa.Column('matchup_avg_plus_minus', sa.Float(), nullable=True),
    sa.Column('matchup_diff_points', sa.Float(), nullable=True),
    sa.Column('matchup_diff_rebounds', sa.Float(), nullable=True),
    sa.Column('matchup_diff_assists', sa.Float(), nullable=True),
    sa.Column('matchup_diff_fg_pct', sa.Float(), nullable=True),
    sa.Column('matchup_diff_plus_minus', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.ForeignKeyConstraint(['opponent_team_id'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'game_id', name='uq_player_game_matchup')
    )
    op.create_index(op.f('ix_matchup_stats_game_date'), 'matchup_stats', ['game_date'], unique=False)
    op.create_index(op.f('ix_matchup_stats_game_id'), 'matchup_stats', ['game_id'], unique=False)
    op.create_index(op.f('ix_matchup_stats_opponent_team_id'), 'matchup_stats', ['opponent_team_id'], unique=False)
    op.create_index(op.f('ix_matchup_stats_player_id'), 'matchup_stats', ['player_id'], unique=False)
    op.create_table('player_advanced_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(length=10), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=True),
    sa.Column('true_shooting_pct', sa.Float(), nullable=True),
    sa.Column('usage_rate', sa.Float(), nullable=True),
    sa.Column('simplified_per', sa.Float(), nullable=True),
    sa.Column('team_fga', sa.Integer(), nullable=True),
    sa.Column('team_fta', sa.Integer(), nullable=True),
    sa.Column('team_tov', sa.Integer(), nullable=True),
    sa.Column('team_minutes', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'game_id', name='uq_player_game_advanced')
    )
    op.create_index(op.f('ix_player_advanced_stats_game_date'), 'player_advanced_stats', ['game_date'], unique=False)
    op.create_index(op.f('ix_player_advanced_stats_game_id'), 'player_advanced_stats', ['game_id'], unique=False)
    op.create_index(op.f('ix_player_advanced_stats_player_id'), 'player_advanced_stats', ['player_id'], unique=False)
    op.create_table('player_rolling_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(length=10), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=True),
    sa.Column('points_avg_5', sa.Float(), nullable=True),
    sa.Column('points_avg_10', sa.Float(), nullable=True),
    sa.Column('points_avg_20', sa.Float(), nullable=True),
    sa.Column('rebounds_avg_5', sa.Float(), nullable=True),
    sa.Column('rebounds_avg_10', sa.Float(), nullable=True),
    sa.Column('rebounds_avg_20', sa.Float(), nullable=True),
    sa.Column('assists_avg_5', sa.Float(), nullable=True),
    sa.Column('assists_avg_10', sa.Float(), nullable=True),
    sa.Column('assists_avg_20', sa.Float(), nullable=True),
    sa.Column('steals_avg_5', sa.Float(), nullable=True),
    sa.Column('steals_avg_10', sa.Float(), nullable=True),
    sa.Column('steals_avg_20', sa.Float(), nullable=True),
    sa.Column('blocks_avg_5', sa.Float(), nullable=True),
    sa.Column('blocks_avg_10', sa.Float(), nullable=True),
    sa.Column('blocks_avg_20', sa.Float(), nullable=True),
    sa.Column('turnovers_avg_5', sa.Float(), nullable=True),
    sa.Column('turnovers_avg_10', sa.Float(), nullable=True),
    sa.Column('turnovers_avg_20', sa.Float(), nullable=True),
    sa.Column('fg_pct_avg_5', sa.Float(), nullable=True),
    sa.Column('fg_pct_avg_10', sa.Float(), nullable=True),
    sa.Column('fg_pct_avg_20', sa.Float(), nullable=True),
    sa.Column('fg3_pct_avg_5', sa.Float(), nullable=True),
    sa.Column('fg3_pct_avg_10', sa.Float(), nullable=True),
    sa.Column('fg3_pct_avg_20', sa.Float(), nullable=True),
    sa.Column('ft_pct_avg_5', sa.Float(), nullable=True),
    sa.Column('ft_pct_avg_10', sa.Float(), nullable=True),
    sa.Column('ft_pct_avg_20', sa.Float(), nullable=True),
    sa.Column('minutes_avg_5', sa.Float(), nullable=True),
    sa.Column('minutes_avg_10', sa.Float(), nullable=True),
    sa.Column('minutes_avg_20', sa.Float(), nullable=True),
    sa.Column('plus_minus_avg_5', sa.Float(), nullable=True),
    sa.Column('plus_minus_avg_10', sa.Float(), nullable=True),
    sa.Column('plus_minus_avg_20', sa.Float(), nullable=True),
    sa.Column('offensive_rebounds_avg_5', sa.Float(), nullable=True),
    sa.Column('offensive_rebounds_avg_10', sa.Float(), nullable=True),
    sa.Column('offensive_rebounds_avg_20', sa.Float(), nullable=True),
    sa.Column('games_available_5', sa.Integer(), nullable=True),
    sa.Column('games_available_10', sa.Integer(), nullable=True),
    sa.Column('games_available_20', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.player_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'game_id', name='uq_player_game_rolling')
    )
    op.create_index(op.f('ix_player_rolling_stats_game_date'), 'player_rolling_stats', ['game_date'], unique=False)
    op.create_index(op.f('ix_player_rolling_stats_game_id'), 'player_rolling_stats', ['game_id'], unique=False)
    op.create_index(op.f('ix_player_rolling_stats_player_id'), 'player_rolling_stats', ['player_id'], unique=False)
    op.create_table('team_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(length=10), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=True),
    sa.Column('pace', sa.Float(), nullable=True),
    sa.Column('offensive_rating', sa.Float(), nullable=True),
    sa.Column('defensive_rating', sa.Float(), nullable=True),
    sa.Column('rest_days', sa.Integer(), nullable=True),
    sa.Column('possessions', sa.Float(), nullable=True),
    sa.Column('opponent_possessions', sa.Float(), nullable=True),
    sa.Column('season_win_pct', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'game_id', name='uq_team_game_features')
    )
    op.create_index(op.f('ix_team_features_game_date'), 'team_features', ['game_date'], unique=False)
    op.create_index(op.f('ix_team_features_game_id'), 'team_features', ['game_id'], unique=False)
    op.create_index(op.f('ix_team_features_team_id'), 'team_features', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_features_team_id'), table_name='team_features')
    op.drop_index(op.f('ix_team_features_game_id'), table_name='team_features')
    op.drop_index(op.f('ix_team_features_game_date'), table_name='team_features')
    op.drop_table('team_features')
    op.drop_index(op.f('ix_player_rolling_stats_player_id'), table_name='player_rolling_stats')
    op.drop_index(op.f('ix_player_rolling_stats_game_id'), table_name='player_rolling_stats')
    op.drop_index(op.f('ix_player_rolling_stats_game_date'), table_name='player_rolling_stats')
    op.drop_table('player_rolling_stats')
    op.drop_index(op.f('ix_player_advanced_stats_player_id'), table_name='player_advanced_stats')
    op.drop_index(op.f('ix_player_advanced_stats_game_id'), table_name='player_advanced_stats')
    op.drop_index(op.f('ix_player_advanced_stats_game_date'), table_name='player_advanced_stats')
    op.drop_table('player_advanced_stats')
    op.drop_index(op.f('ix_matchup_stats_player_id'), table_name='matchup_stats')
    op.drop_index(op.f('ix_matchup_stats_opponent_team_id'), table_name='matchup_stats')
    op.drop_index(op.f('ix_matchup_stats_game_id'), table_name='matchup_stats')
    op.drop_index(op.f('ix_matchup_stats_game_date'), table_name='matchup_stats')
    op.drop_table('matchup_stats')
    # ### end Alembic commands ###
